// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: cache.proto

package cache

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KV Messages
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DelResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{6}
}

func (x *ExistsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{7}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Hash Messages
type HSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSetRequest) Reset() {
	*x = HSetRequest{}
	mi := &file_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetRequest) ProtoMessage() {}

func (x *HSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetRequest.ProtoReflect.Descriptor instead.
func (*HSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{8}
}

func (x *HSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HSetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *HSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // true if new field, false if updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSetResponse) Reset() {
	*x = HSetResponse{}
	mi := &file_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetResponse) ProtoMessage() {}

func (x *HSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetResponse.ProtoReflect.Descriptor instead.
func (*HSetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{9}
}

func (x *HSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HSetResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type HGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetRequest) Reset() {
	*x = HGetRequest{}
	mi := &file_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetRequest) ProtoMessage() {}

func (x *HGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetRequest.ProtoReflect.Descriptor instead.
func (*HGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{10}
}

func (x *HGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HGetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type HGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetResponse) Reset() {
	*x = HGetResponse{}
	mi := &file_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetResponse) ProtoMessage() {}

func (x *HGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetResponse.ProtoReflect.Descriptor instead.
func (*HGetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{11}
}

func (x *HGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *HGetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type HDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HDelRequest) Reset() {
	*x = HDelRequest{}
	mi := &file_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelRequest) ProtoMessage() {}

func (x *HDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelRequest.ProtoReflect.Descriptor instead.
func (*HDelRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{12}
}

func (x *HDelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HDelRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type HDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HDelResponse) Reset() {
	*x = HDelResponse{}
	mi := &file_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelResponse) ProtoMessage() {}

func (x *HDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelResponse.ProtoReflect.Descriptor instead.
func (*HDelResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{13}
}

func (x *HDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HDelResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type HMSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // field -> value mapping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMSetRequest) Reset() {
	*x = HMSetRequest{}
	mi := &file_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMSetRequest) ProtoMessage() {}

func (x *HMSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMSetRequest.ProtoReflect.Descriptor instead.
func (*HMSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{14}
}

func (x *HMSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HMSetRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HMSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // number of fields set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMSetResponse) Reset() {
	*x = HMSetResponse{}
	mi := &file_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMSetResponse) ProtoMessage() {}

func (x *HMSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMSetResponse.ProtoReflect.Descriptor instead.
func (*HMSetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{15}
}

func (x *HMSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HMSetResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type HMGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMGetRequest) Reset() {
	*x = HMGetRequest{}
	mi := &file_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMGetRequest) ProtoMessage() {}

func (x *HMGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMGetRequest.ProtoReflect.Descriptor instead.
func (*HMGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{16}
}

func (x *HMGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HMGetRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HMGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // field -> value mapping (only existing fields)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HMGetResponse) Reset() {
	*x = HMGetResponse{}
	mi := &file_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HMGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HMGetResponse) ProtoMessage() {}

func (x *HMGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HMGetResponse.ProtoReflect.Descriptor instead.
func (*HMGetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{17}
}

func (x *HMGetResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HLenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLenRequest) Reset() {
	*x = HLenRequest{}
	mi := &file_cache_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLenRequest) ProtoMessage() {}

func (x *HLenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLenRequest.ProtoReflect.Descriptor instead.
func (*HLenRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{18}
}

func (x *HLenRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HLenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLenResponse) Reset() {
	*x = HLenResponse{}
	mi := &file_cache_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLenResponse) ProtoMessage() {}

func (x *HLenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLenResponse.ProtoReflect.Descriptor instead.
func (*HLenResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{19}
}

func (x *HLenResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type HGetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetAllRequest) Reset() {
	*x = HGetAllRequest{}
	mi := &file_cache_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllRequest) ProtoMessage() {}

func (x *HGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllRequest.ProtoReflect.Descriptor instead.
func (*HGetAllRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{20}
}

func (x *HGetAllRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HGetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // all field -> value pairs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetAllResponse) Reset() {
	*x = HGetAllResponse{}
	mi := &file_cache_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllResponse) ProtoMessage() {}

func (x *HGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllResponse.ProtoReflect.Descriptor instead.
func (*HGetAllResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{21}
}

func (x *HGetAllResponse) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HExistsRequest) Reset() {
	*x = HExistsRequest{}
	mi := &file_cache_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExistsRequest) ProtoMessage() {}

func (x *HExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExistsRequest.ProtoReflect.Descriptor instead.
func (*HExistsRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{22}
}

func (x *HExistsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HExistsRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type HExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HExistsResponse) Reset() {
	*x = HExistsResponse{}
	mi := &file_cache_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HExistsResponse) ProtoMessage() {}

func (x *HExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HExistsResponse.ProtoReflect.Descriptor instead.
func (*HExistsResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{23}
}

func (x *HExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Set Messages
type SAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAddRequest) Reset() {
	*x = SAddRequest{}
	mi := &file_cache_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRequest) ProtoMessage() {}

func (x *SAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRequest.ProtoReflect.Descriptor instead.
func (*SAddRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{24}
}

func (x *SAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SAddRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Added         bool                   `protobuf:"varint,2,opt,name=added,proto3" json:"added,omitempty"` // true if new member, false if already exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAddResponse) Reset() {
	*x = SAddResponse{}
	mi := &file_cache_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddResponse) ProtoMessage() {}

func (x *SAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddResponse.ProtoReflect.Descriptor instead.
func (*SAddResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{25}
}

func (x *SAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SAddResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type SMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMembersRequest) Reset() {
	*x = SMembersRequest{}
	mi := &file_cache_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRequest) ProtoMessage() {}

func (x *SMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRequest.ProtoReflect.Descriptor instead.
func (*SMembersRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{26}
}

func (x *SMembersRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMembersResponse) Reset() {
	*x = SMembersResponse{}
	mi := &file_cache_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersResponse) ProtoMessage() {}

func (x *SMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersResponse.ProtoReflect.Descriptor instead.
func (*SMembersResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{27}
}

func (x *SMembersResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SRemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRemRequest) Reset() {
	*x = SRemRequest{}
	mi := &file_cache_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemRequest) ProtoMessage() {}

func (x *SRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemRequest.ProtoReflect.Descriptor instead.
func (*SRemRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{28}
}

func (x *SRemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SRemRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SRemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRemResponse) Reset() {
	*x = SRemResponse{}
	mi := &file_cache_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemResponse) ProtoMessage() {}

func (x *SRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemResponse.ProtoReflect.Descriptor instead.
func (*SRemResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{29}
}

func (x *SRemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SRemResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type SIsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIsMemberRequest) Reset() {
	*x = SIsMemberRequest{}
	mi := &file_cache_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberRequest) ProtoMessage() {}

func (x *SIsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberRequest.ProtoReflect.Descriptor instead.
func (*SIsMemberRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{30}
}

func (x *SIsMemberRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SIsMemberRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SIsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIsMemberResponse) Reset() {
	*x = SIsMemberResponse{}
	mi := &file_cache_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberResponse) ProtoMessage() {}

func (x *SIsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberResponse.ProtoReflect.Descriptor instead.
func (*SIsMemberResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{31}
}

func (x *SIsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type SCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SCardRequest) Reset() {
	*x = SCardRequest{}
	mi := &file_cache_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardRequest) ProtoMessage() {}

func (x *SCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardRequest.ProtoReflect.Descriptor instead.
func (*SCardRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{32}
}

func (x *SCardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cardinality   int32                  `protobuf:"varint,1,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SCardResponse) Reset() {
	*x = SCardResponse{}
	mi := &file_cache_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardResponse) ProtoMessage() {}

func (x *SCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardResponse.ProtoReflect.Descriptor instead.
func (*SCardResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{33}
}

func (x *SCardResponse) GetCardinality() int32 {
	if x != nil {
		return x.Cardinality
	}
	return 0
}

// List Messages
type LPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPushRequest) Reset() {
	*x = LPushRequest{}
	mi := &file_cache_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushRequest) ProtoMessage() {}

func (x *LPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushRequest.ProtoReflect.Descriptor instead.
func (*LPushRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{34}
}

func (x *LPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LPushRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"` // new length of list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPushResponse) Reset() {
	*x = LPushResponse{}
	mi := &file_cache_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushResponse) ProtoMessage() {}

func (x *LPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushResponse.ProtoReflect.Descriptor instead.
func (*LPushResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{35}
}

func (x *LPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LPushResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Stop          int32                  `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeRequest) Reset() {
	*x = LRangeRequest{}
	mi := &file_cache_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRequest) ProtoMessage() {}

func (x *LRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRequest.ProtoReflect.Descriptor instead.
func (*LRangeRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{36}
}

func (x *LRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LRangeRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LRangeRequest) GetStop() int32 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type LRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeResponse) Reset() {
	*x = LRangeResponse{}
	mi := &file_cache_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeResponse) ProtoMessage() {}

func (x *LRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeResponse.ProtoReflect.Descriptor instead.
func (*LRangeResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{37}
}

func (x *LRangeResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LRemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRemRequest) Reset() {
	*x = LRemRequest{}
	mi := &file_cache_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRemRequest) ProtoMessage() {}

func (x *LRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRemRequest.ProtoReflect.Descriptor instead.
func (*LRemRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{38}
}

func (x *LRemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LRemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LRemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LRemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRemResponse) Reset() {
	*x = LRemResponse{}
	mi := &file_cache_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRemResponse) ProtoMessage() {}

func (x *LRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRemResponse.ProtoReflect.Descriptor instead.
func (*LRemResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{39}
}

func (x *LRemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LRemResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type LPopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPopRequest) Reset() {
	*x = LPopRequest{}
	mi := &file_cache_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRequest) ProtoMessage() {}

func (x *LPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRequest.ProtoReflect.Descriptor instead.
func (*LPopRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{40}
}

func (x *LPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LPopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPopResponse) Reset() {
	*x = LPopResponse{}
	mi := &file_cache_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopResponse) ProtoMessage() {}

func (x *LPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopResponse.ProtoReflect.Descriptor instead.
func (*LPopResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{41}
}

func (x *LPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPushRequest) Reset() {
	*x = RPushRequest{}
	mi := &file_cache_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushRequest) ProtoMessage() {}

func (x *RPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushRequest.ProtoReflect.Descriptor instead.
func (*RPushRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{42}
}

func (x *RPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RPushRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPushResponse) Reset() {
	*x = RPushResponse{}
	mi := &file_cache_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushResponse) ProtoMessage() {}

func (x *RPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushResponse.ProtoReflect.Descriptor instead.
func (*RPushResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{43}
}

func (x *RPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RPushResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RPopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPopRequest) Reset() {
	*x = RPopRequest{}
	mi := &file_cache_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopRequest) ProtoMessage() {}

func (x *RPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopRequest.ProtoReflect.Descriptor instead.
func (*RPopRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{44}
}

func (x *RPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RPopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPopResponse) Reset() {
	*x = RPopResponse{}
	mi := &file_cache_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopResponse) ProtoMessage() {}

func (x *RPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopResponse.ProtoReflect.Descriptor instead.
func (*RPopResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{45}
}

func (x *RPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LLenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLenRequest) Reset() {
	*x = LLenRequest{}
	mi := &file_cache_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenRequest) ProtoMessage() {}

func (x *LLenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenRequest.ProtoReflect.Descriptor instead.
func (*LLenRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{46}
}

func (x *LLenRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LLenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLenResponse) Reset() {
	*x = LLenResponse{}
	mi := &file_cache_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLenResponse) ProtoMessage() {}

func (x *LLenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLenResponse.ProtoReflect.Descriptor instead.
func (*LLenResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{47}
}

func (x *LLenResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LIndexRequest) Reset() {
	*x = LIndexRequest{}
	mi := &file_cache_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIndexRequest) ProtoMessage() {}

func (x *LIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIndexRequest.ProtoReflect.Descriptor instead.
func (*LIndexRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{48}
}

func (x *LIndexRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LIndexRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type LIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LIndexResponse) Reset() {
	*x = LIndexResponse{}
	mi := &file_cache_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LIndexResponse) ProtoMessage() {}

func (x *LIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LIndexResponse.ProtoReflect.Descriptor instead.
func (*LIndexResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{49}
}

func (x *LIndexResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LIndexResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type LSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSetRequest) Reset() {
	*x = LSetRequest{}
	mi := &file_cache_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSetRequest) ProtoMessage() {}

func (x *LSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSetRequest.ProtoReflect.Descriptor instead.
func (*LSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{50}
}

func (x *LSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LSetRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LSetResponse) Reset() {
	*x = LSetResponse{}
	mi := &file_cache_proto_msgTypes[51]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSetResponse) ProtoMessage() {}

func (x *LSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[51]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSetResponse.ProtoReflect.Descriptor instead.
func (*LSetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{51}
}

func (x *LSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\x05cache\x1a\x1cgoogle/api/annotations.proto\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"\x1e\n" +
	"\n" +
	"DelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\vDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\"!\n" +
	"\rExistsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"K\n" +
	"\vHSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"B\n" +
	"\fHSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"5\n" +
	"\vHGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"<\n" +
	"\fHGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"5\n" +
	"\vHDelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"M\n" +
	"\fHDelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\"\x94\x01\n" +
	"\fHMSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x06fields\x18\x02 \x03(\v2\x1f.cache.HMSetRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\rHMSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"8\n" +
	"\fHMGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"\x84\x01\n" +
	"\rHMGetResponse\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .cache.HMGetResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\vHLenRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\fHLenResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\"\"\n" +
	"\x0eHGetAllRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x88\x01\n" +
	"\x0fHGetAllResponse\x12:\n" +
	"\x06fields\x18\x01 \x03(\v2\".cache.HGetAllResponse.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x0eHExistsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\")\n" +
	"\x0fHExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"7\n" +
	"\vSAddRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\">\n" +
	"\fSAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05added\x18\x02 \x01(\bR\x05added\"#\n" +
	"\x0fSMembersRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\",\n" +
	"\x10SMembersResponse\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\"7\n" +
	"\vSRemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"M\n" +
	"\fSRemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\"<\n" +
	"\x10SIsMemberRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"0\n" +
	"\x11SIsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\" \n" +
	"\fSCardRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"1\n" +
	"\rSCardResponse\x12 \n" +
	"\vcardinality\x18\x01 \x01(\x05R\vcardinality\"6\n" +
	"\fLPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\rLPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"K\n" +
	"\rLRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\x05R\x04stop\"(\n" +
	"\x0eLRangeResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"K\n" +
	"\vLRemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"M\n" +
	"\fLRemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\"\x1f\n" +
	"\vLPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\">\n" +
	"\fLPopResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"6\n" +
	"\fRPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"A\n" +
	"\rRPushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"\x1f\n" +
	"\vRPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\">\n" +
	"\fRPopResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x1f\n" +
	"\vLLenRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\fLLenResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\"7\n" +
	"\rLIndexRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\">\n" +
	"\x0eLIndexResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"K\n" +
	"\vLSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"(\n" +
	"\fLSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc7\x10\n" +
	"\fCacheService\x12C\n" +
	"\x03Set\x12\x11.cache.SetRequest\x1a\x12.cache.SetResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/kv/set\x12F\n" +
	"\x03Get\x12\x11.cache.GetRequest\x1a\x12.cache.GetResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/kv/get/{key}\x12F\n" +
	"\x03Del\x12\x11.cache.DelRequest\x1a\x12.cache.DelResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/kv/del/{key}\x12R\n" +
	"\x06Exists\x12\x14.cache.ExistsRequest\x1a\x15.cache.ExistsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/kv/exists/{key}\x12H\n" +
	"\x04HSet\x12\x12.cache.HSetRequest\x1a\x13.cache.HSetResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/hash/set\x12S\n" +
	"\x04HGet\x12\x12.cache.HGetRequest\x1a\x13.cache.HGetResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/hash/get/{key}/{field}\x12S\n" +
	"\x04HDel\x12\x12.cache.HDelRequest\x1a\x13.cache.HDelResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/hash/del/{key}/{field}\x12L\n" +
	"\x05HMSet\x12\x13.cache.HMSetRequest\x1a\x14.cache.HMSetResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/hash/mset\x12L\n" +
	"\x05HMGet\x12\x13.cache.HMGetRequest\x1a\x14.cache.HMGetResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/hash/mget\x12K\n" +
	"\x04HLen\x12\x12.cache.HLenRequest\x1a\x13.cache.HLenResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/hash/len/{key}\x12W\n" +
	"\aHGetAll\x12\x15.cache.HGetAllRequest\x1a\x16.cache.HGetAllResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/hash/getall/{key}\x12_\n" +
	"\aHExists\x12\x15.cache.HExistsRequest\x1a\x16.cache.HExistsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/hash/exists/{key}/{field}\x12G\n" +
	"\x04SAdd\x12\x12.cache.SAddRequest\x1a\x13.cache.SAddResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/set/add\x12Z\n" +
	"\bSMembers\x12\x16.cache.SMembersRequest\x1a\x17.cache.SMembersResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/set/members/{key}\x12S\n" +
	"\x04SRem\x12\x12.cache.SRemRequest\x1a\x13.cache.SRemResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/set/rem/{key}/{member}\x12g\n" +
	"\tSIsMember\x12\x17.cache.SIsMemberRequest\x1a\x18.cache.SIsMemberResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/set/ismember/{key}/{member}\x12N\n" +
	"\x05SCard\x12\x13.cache.SCardRequest\x1a\x14.cache.SCardResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/set/card/{key}\x12L\n" +
	"\x05LPush\x12\x13.cache.LPushRequest\x1a\x14.cache.LPushResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/list/push\x12S\n" +
	"\x06LRange\x12\x14.cache.LRangeRequest\x1a\x15.cache.LRangeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/list/range/{key}\x12H\n" +
	"\x04LRem\x12\x12.cache.LRemRequest\x1a\x13.cache.LRemResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/list/rem\x12I\n" +
	"\x04LPop\x12\x12.cache.LPopRequest\x1a\x13.cache.LPopResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/list/lpop\x12M\n" +
	"\x05RPush\x12\x13.cache.RPushRequest\x1a\x14.cache.RPushResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/list/rpush\x12I\n" +
	"\x04RPop\x12\x12.cache.RPopRequest\x1a\x13.cache.RPopResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/list/rpop\x12K\n" +
	"\x04LLen\x12\x12.cache.LLenRequest\x1a\x13.cache.LLenResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/list/len/{key}\x12[\n" +
	"\x06LIndex\x12\x14.cache.LIndexRequest\x1a\x15.cache.LIndexResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/list/index/{key}/{index}\x12H\n" +
	"\x04LSet\x12\x12.cache.LSetRequest\x1a\x13.cache.LSetResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/list/setB)Z'github.com/yoitsuholo/relax/proto;cacheb\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 55)
var file_cache_proto_goTypes = []any{
	(*SetRequest)(nil),        // 0: cache.SetRequest
	(*SetResponse)(nil),       // 1: cache.SetResponse
	(*GetRequest)(nil),        // 2: cache.GetRequest
	(*GetResponse)(nil),       // 3: cache.GetResponse
	(*DelRequest)(nil),        // 4: cache.DelRequest
	(*DelResponse)(nil),       // 5: cache.DelResponse
	(*ExistsRequest)(nil),     // 6: cache.ExistsRequest
	(*ExistsResponse)(nil),    // 7: cache.ExistsResponse
	(*HSetRequest)(nil),       // 8: cache.HSetRequest
	(*HSetResponse)(nil),      // 9: cache.HSetResponse
	(*HGetRequest)(nil),       // 10: cache.HGetRequest
	(*HGetResponse)(nil),      // 11: cache.HGetResponse
	(*HDelRequest)(nil),       // 12: cache.HDelRequest
	(*HDelResponse)(nil),      // 13: cache.HDelResponse
	(*HMSetRequest)(nil),      // 14: cache.HMSetRequest
	(*HMSetResponse)(nil),     // 15: cache.HMSetResponse
	(*HMGetRequest)(nil),      // 16: cache.HMGetRequest
	(*HMGetResponse)(nil),     // 17: cache.HMGetResponse
	(*HLenRequest)(nil),       // 18: cache.HLenRequest
	(*HLenResponse)(nil),      // 19: cache.HLenResponse
	(*HGetAllRequest)(nil),    // 20: cache.HGetAllRequest
	(*HGetAllResponse)(nil),   // 21: cache.HGetAllResponse
	(*HExistsRequest)(nil),    // 22: cache.HExistsRequest
	(*HExistsResponse)(nil),   // 23: cache.HExistsResponse
	(*SAddRequest)(nil),       // 24: cache.SAddRequest
	(*SAddResponse)(nil),      // 25: cache.SAddResponse
	(*SMembersRequest)(nil),   // 26: cache.SMembersRequest
	(*SMembersResponse)(nil),  // 27: cache.SMembersResponse
	(*SRemRequest)(nil),       // 28: cache.SRemRequest
	(*SRemResponse)(nil),      // 29: cache.SRemResponse
	(*SIsMemberRequest)(nil),  // 30: cache.SIsMemberRequest
	(*SIsMemberResponse)(nil), // 31: cache.SIsMemberResponse
	(*SCardRequest)(nil),      // 32: cache.SCardRequest
	(*SCardResponse)(nil),     // 33: cache.SCardResponse
	(*LPushRequest)(nil),      // 34: cache.LPushRequest
	(*LPushResponse)(nil),     // 35: cache.LPushResponse
	(*LRangeRequest)(nil),     // 36: cache.LRangeRequest
	(*LRangeResponse)(nil),    // 37: cache.LRangeResponse
	(*LRemRequest)(nil),       // 38: cache.LRemRequest
	(*LRemResponse)(nil),      // 39: cache.LRemResponse
	(*LPopRequest)(nil),       // 40: cache.LPopRequest
	(*LPopResponse)(nil),      // 41: cache.LPopResponse
	(*RPushRequest)(nil),      // 42: cache.RPushRequest
	(*RPushResponse)(nil),     // 43: cache.RPushResponse
	(*RPopRequest)(nil),       // 44: cache.RPopRequest
	(*RPopResponse)(nil),      // 45: cache.RPopResponse
	(*LLenRequest)(nil),       // 46: cache.LLenRequest
	(*LLenResponse)(nil),      // 47: cache.LLenResponse
	(*LIndexRequest)(nil),     // 48: cache.LIndexRequest
	(*LIndexResponse)(nil),    // 49: cache.LIndexResponse
	(*LSetRequest)(nil),       // 50: cache.LSetRequest
	(*LSetResponse)(nil),      // 51: cache.LSetResponse
	nil,                       // 52: cache.HMSetRequest.FieldsEntry
	nil,                       // 53: cache.HMGetResponse.ValuesEntry
	nil,                       // 54: cache.HGetAllResponse.FieldsEntry
}
var file_cache_proto_depIdxs = []int32{
	52, // 0: cache.HMSetRequest.fields:type_name -> cache.HMSetRequest.FieldsEntry
	53, // 1: cache.HMGetResponse.values:type_name -> cache.HMGetResponse.ValuesEntry
	54, // 2: cache.HGetAllResponse.fields:type_name -> cache.HGetAllResponse.FieldsEntry
	0,  // 3: cache.CacheService.Set:input_type -> cache.SetRequest
	2,  // 4: cache.CacheService.Get:input_type -> cache.GetRequest
	4,  // 5: cache.CacheService.Del:input_type -> cache.DelRequest
	6,  // 6: cache.CacheService.Exists:input_type -> cache.ExistsRequest
	8,  // 7: cache.CacheService.HSet:input_type -> cache.HSetRequest
	10, // 8: cache.CacheService.HGet:input_type -> cache.HGetRequest
	12, // 9: cache.CacheService.HDel:input_type -> cache.HDelRequest
	14, // 10: cache.CacheService.HMSet:input_type -> cache.HMSetRequest
	16, // 11: cache.CacheService.HMGet:input_type -> cache.HMGetRequest
	18, // 12: cache.CacheService.HLen:input_type -> cache.HLenRequest
	20, // 13: cache.CacheService.HGetAll:input_type -> cache.HGetAllRequest
	22, // 14: cache.CacheService.HExists:input_type -> cache.HExistsRequest
	24, // 15: cache.CacheService.SAdd:input_type -> cache.SAddRequest
	26, // 16: cache.CacheService.SMembers:input_type -> cache.SMembersRequest
	28, // 17: cache.CacheService.SRem:input_type -> cache.SRemRequest
	30, // 18: cache.CacheService.SIsMember:input_type -> cache.SIsMemberRequest
	32, // 19: cache.CacheService.SCard:input_type -> cache.SCardRequest
	34, // 20: cache.CacheService.LPush:input_type -> cache.LPushRequest
	36, // 21: cache.CacheService.LRange:input_type -> cache.LRangeRequest
	38, // 22: cache.CacheService.LRem:input_type -> cache.LRemRequest
	40, // 23: cache.CacheService.LPop:input_type -> cache.LPopRequest
	42, // 24: cache.CacheService.RPush:input_type -> cache.RPushRequest
	44, // 25: cache.CacheService.RPop:input_type -> cache.RPopRequest
	46, // 26: cache.CacheService.LLen:input_type -> cache.LLenRequest
	48, // 27: cache.CacheService.LIndex:input_type -> cache.LIndexRequest
	50, // 28: cache.CacheService.LSet:input_type -> cache.LSetRequest
	1,  // 29: cache.CacheService.Set:output_type -> cache.SetResponse
	3,  // 30: cache.CacheService.Get:output_type -> cache.GetResponse
	5,  // 31: cache.CacheService.Del:output_type -> cache.DelResponse
	7,  // 32: cache.CacheService.Exists:output_type -> cache.ExistsResponse
	9,  // 33: cache.CacheService.HSet:output_type -> cache.HSetResponse
	11, // 34: cache.CacheService.HGet:output_type -> cache.HGetResponse
	13, // 35: cache.CacheService.HDel:output_type -> cache.HDelResponse
	15, // 36: cache.CacheService.HMSet:output_type -> cache.HMSetResponse
	17, // 37: cache.CacheService.HMGet:output_type -> cache.HMGetResponse
	19, // 38: cache.CacheService.HLen:output_type -> cache.HLenResponse
	21, // 39: cache.CacheService.HGetAll:output_type -> cache.HGetAllResponse
	23, // 40: cache.CacheService.HExists:output_type -> cache.HExistsResponse
	25, // 41: cache.CacheService.SAdd:output_type -> cache.SAddResponse
	27, // 42: cache.CacheService.SMembers:output_type -> cache.SMembersResponse
	29, // 43: cache.CacheService.SRem:output_type -> cache.SRemResponse
	31, // 44: cache.CacheService.SIsMember:output_type -> cache.SIsMemberResponse
	33, // 45: cache.CacheService.SCard:output_type -> cache.SCardResponse
	35, // 46: cache.CacheService.LPush:output_type -> cache.LPushResponse
	37, // 47: cache.CacheService.LRange:output_type -> cache.LRangeResponse
	39, // 48: cache.CacheService.LRem:output_type -> cache.LRemResponse
	41, // 49: cache.CacheService.LPop:output_type -> cache.LPopResponse
	43, // 50: cache.CacheService.RPush:output_type -> cache.RPushResponse
	45, // 51: cache.CacheService.RPop:output_type -> cache.RPopResponse
	47, // 52: cache.CacheService.LLen:output_type -> cache.LLenResponse
	49, // 53: cache.CacheService.LIndex:output_type -> cache.LIndexResponse
	51, // 54: cache.CacheService.LSet:output_type -> cache.LSetResponse
	29, // [29:55] is the sub-list for method output_type
	3,  // [3:29] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   55,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
