// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: cache.proto

package cache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheService_KvSet_FullMethodName       = "/cache.CacheService/KvSet"
	CacheService_KvGet_FullMethodName       = "/cache.CacheService/KvGet"
	CacheService_KvDel_FullMethodName       = "/cache.CacheService/KvDel"
	CacheService_KvExists_FullMethodName    = "/cache.CacheService/KvExists"
	CacheService_HashSet_FullMethodName     = "/cache.CacheService/HashSet"
	CacheService_HashGet_FullMethodName     = "/cache.CacheService/HashGet"
	CacheService_HashDel_FullMethodName     = "/cache.CacheService/HashDel"
	CacheService_HashExists_FullMethodName  = "/cache.CacheService/HashExists"
	CacheService_HashLen_FullMethodName     = "/cache.CacheService/HashLen"
	CacheService_HashSetM_FullMethodName    = "/cache.CacheService/HashSetM"
	CacheService_HashGetM_FullMethodName    = "/cache.CacheService/HashGetM"
	CacheService_HashDelM_FullMethodName    = "/cache.CacheService/HashDelM"
	CacheService_HashExistsM_FullMethodName = "/cache.CacheService/HashExistsM"
	CacheService_SetSet_FullMethodName      = "/cache.CacheService/SetSet"
	CacheService_SetGet_FullMethodName      = "/cache.CacheService/SetGet"
	CacheService_SetDel_FullMethodName      = "/cache.CacheService/SetDel"
	CacheService_SetExists_FullMethodName   = "/cache.CacheService/SetExists"
	CacheService_SetLen_FullMethodName      = "/cache.CacheService/SetLen"
	CacheService_SetAddM_FullMethodName     = "/cache.CacheService/SetAddM"
	CacheService_SetExistsM_FullMethodName  = "/cache.CacheService/SetExistsM"
	CacheService_SetDelM_FullMethodName     = "/cache.CacheService/SetDelM"
	CacheService_SetGetM_FullMethodName     = "/cache.CacheService/SetGetM"
	CacheService_Set_FullMethodName         = "/cache.CacheService/Set"
	CacheService_Get_FullMethodName         = "/cache.CacheService/Get"
	CacheService_Del_FullMethodName         = "/cache.CacheService/Del"
	CacheService_Exists_FullMethodName      = "/cache.CacheService/Exists"
	CacheService_HMSet_FullMethodName       = "/cache.CacheService/HMSet"
	CacheService_HMGet_FullMethodName       = "/cache.CacheService/HMGet"
	CacheService_HLen_FullMethodName        = "/cache.CacheService/HLen"
	CacheService_HGetAll_FullMethodName     = "/cache.CacheService/HGetAll"
	CacheService_HDel_FullMethodName        = "/cache.CacheService/HDel"
	CacheService_HExists_FullMethodName     = "/cache.CacheService/HExists"
	CacheService_SAdd_FullMethodName        = "/cache.CacheService/SAdd"
	CacheService_SIsMember_FullMethodName   = "/cache.CacheService/SIsMember"
	CacheService_SCard_FullMethodName       = "/cache.CacheService/SCard"
	CacheService_SMembers_FullMethodName    = "/cache.CacheService/SMembers"
	CacheService_SRem_FullMethodName        = "/cache.CacheService/SRem"
	CacheService_LPush_FullMethodName       = "/cache.CacheService/LPush"
	CacheService_LRange_FullMethodName      = "/cache.CacheService/LRange"
	CacheService_LRem_FullMethodName        = "/cache.CacheService/LRem"
	CacheService_LPop_FullMethodName        = "/cache.CacheService/LPop"
	CacheService_RPush_FullMethodName       = "/cache.CacheService/RPush"
	CacheService_RPop_FullMethodName        = "/cache.CacheService/RPop"
	CacheService_LLen_FullMethodName        = "/cache.CacheService/LLen"
	CacheService_LIndex_FullMethodName      = "/cache.CacheService/LIndex"
	CacheService_LSet_FullMethodName        = "/cache.CacheService/LSet"
)

// CacheServiceClient is the client API for CacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CacheService provides Redis-like cache operations
type CacheServiceClient interface {
	// ---------- KV Native Operations ----------
	KvSet(ctx context.Context, in *KvSetRequest, opts ...grpc.CallOption) (*KvSetResponse, error)
	KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error)
	KvDel(ctx context.Context, in *KvDelRequest, opts ...grpc.CallOption) (*KvDelResponse, error)
	KvExists(ctx context.Context, in *KvExistsRequest, opts ...grpc.CallOption) (*KvExistsResponse, error)
	// ---------- Hash Native Operations ----------
	// Batch/whole hash operations
	HashSet(ctx context.Context, in *HashSetRequest, opts ...grpc.CallOption) (*HashSetResponse, error)
	HashGet(ctx context.Context, in *HashGetRequest, opts ...grpc.CallOption) (*HashGetResponse, error)
	HashDel(ctx context.Context, in *HashDelRequest, opts ...grpc.CallOption) (*HashDelResponse, error)
	HashExists(ctx context.Context, in *HashExistsRequest, opts ...grpc.CallOption) (*HashExistsResponse, error)
	HashLen(ctx context.Context, in *HashLenRequest, opts ...grpc.CallOption) (*HashLenResponse, error)
	// Single field operations
	HashSetM(ctx context.Context, in *HashSetMRequest, opts ...grpc.CallOption) (*HashSetMResponse, error)
	HashGetM(ctx context.Context, in *HashGetMRequest, opts ...grpc.CallOption) (*HashGetMResponse, error)
	HashDelM(ctx context.Context, in *HashDelMRequest, opts ...grpc.CallOption) (*HashDelMResponse, error)
	HashExistsM(ctx context.Context, in *HashExistsMRequest, opts ...grpc.CallOption) (*HashExistsMResponse, error)
	// ---------- Set Native Operations ----------
	// Batch/whole set operations
	SetSet(ctx context.Context, in *SetSetRequest, opts ...grpc.CallOption) (*SetSetResponse, error)
	SetGet(ctx context.Context, in *SetGetRequest, opts ...grpc.CallOption) (*SetGetResponse, error)
	SetDel(ctx context.Context, in *SetDelRequest, opts ...grpc.CallOption) (*SetDelResponse, error)
	SetExists(ctx context.Context, in *SetExistsRequest, opts ...grpc.CallOption) (*SetExistsResponse, error)
	SetLen(ctx context.Context, in *SetLenRequest, opts ...grpc.CallOption) (*SetLenResponse, error)
	// Single member operations
	SetAddM(ctx context.Context, in *SetAddMRequest, opts ...grpc.CallOption) (*SetAddMResponse, error)
	SetExistsM(ctx context.Context, in *SetExistsMRequest, opts ...grpc.CallOption) (*SetExistsMResponse, error)
	SetDelM(ctx context.Context, in *SetDelMRequest, opts ...grpc.CallOption) (*SetDelMResponse, error)
	SetGetM(ctx context.Context, in *SetGetMRequest, opts ...grpc.CallOption) (*SetGetMResponse, error)
	// ---------- KV Redis Aliases ----------
	// SET -> forwards to KvSet
	Set(ctx context.Context, in *KvSetRequest, opts ...grpc.CallOption) (*KvSetResponse, error)
	// GET -> forwards to KvGet
	Get(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error)
	// DEL -> forwards to KvDel
	Del(ctx context.Context, in *KvDelRequest, opts ...grpc.CallOption) (*KvDelResponse, error)
	// EXISTS -> forwards to KvExists
	Exists(ctx context.Context, in *KvExistsRequest, opts ...grpc.CallOption) (*KvExistsResponse, error)
	// ---------- Hash Redis Aliases ----------
	// HMSET -> forwards to HashSetM (set single field)
	HMSet(ctx context.Context, in *HashSetMRequest, opts ...grpc.CallOption) (*HashSetMResponse, error)
	// HMGET -> forwards to HashGetM (get single field)
	HMGet(ctx context.Context, in *HashGetMRequest, opts ...grpc.CallOption) (*HashGetMResponse, error)
	// HLEN -> forwards to HashLen
	HLen(ctx context.Context, in *HashLenRequest, opts ...grpc.CallOption) (*HashLenResponse, error)
	// HGETALL -> forwards to HashGet (get all fields)
	HGetAll(ctx context.Context, in *HashGetRequest, opts ...grpc.CallOption) (*HashGetResponse, error)
	// HDEL -> forwards to HashDel (delete entire hash)
	HDel(ctx context.Context, in *HashDelRequest, opts ...grpc.CallOption) (*HashDelResponse, error)
	// HEXISTS -> forwards to HashExistsM (check field exists)
	HExists(ctx context.Context, in *HashExistsMRequest, opts ...grpc.CallOption) (*HashExistsMResponse, error)
	// ---------- Set Redis Aliases ----------
	// SADD -> forwards to SetAddM (add single member)
	SAdd(ctx context.Context, in *SetAddMRequest, opts ...grpc.CallOption) (*SetAddMResponse, error)
	// SISMEMBER -> forwards to SetExistsM (check member exists)
	SIsMember(ctx context.Context, in *SetExistsMRequest, opts ...grpc.CallOption) (*SetExistsMResponse, error)
	// SCARD -> forwards to SetLen (get member count)
	SCard(ctx context.Context, in *SetLenRequest, opts ...grpc.CallOption) (*SetLenResponse, error)
	// SMEMBERS -> forwards to SetGet (get all members)
	SMembers(ctx context.Context, in *SetGetRequest, opts ...grpc.CallOption) (*SetGetResponse, error)
	// SREM -> forwards to SetDelM (remove single member)
	SRem(ctx context.Context, in *SetDelMRequest, opts ...grpc.CallOption) (*SetDelMResponse, error)
	// List operations
	LPush(ctx context.Context, in *LPushRequest, opts ...grpc.CallOption) (*LPushResponse, error)
	LRange(ctx context.Context, in *LRangeRequest, opts ...grpc.CallOption) (*LRangeResponse, error)
	LRem(ctx context.Context, in *LRemRequest, opts ...grpc.CallOption) (*LRemResponse, error)
	LPop(ctx context.Context, in *LPopRequest, opts ...grpc.CallOption) (*LPopResponse, error)
	RPush(ctx context.Context, in *RPushRequest, opts ...grpc.CallOption) (*RPushResponse, error)
	RPop(ctx context.Context, in *RPopRequest, opts ...grpc.CallOption) (*RPopResponse, error)
	LLen(ctx context.Context, in *LLenRequest, opts ...grpc.CallOption) (*LLenResponse, error)
	LIndex(ctx context.Context, in *LIndexRequest, opts ...grpc.CallOption) (*LIndexResponse, error)
	LSet(ctx context.Context, in *LSetRequest, opts ...grpc.CallOption) (*LSetResponse, error)
}

type cacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheServiceClient(cc grpc.ClientConnInterface) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) KvSet(ctx context.Context, in *KvSetRequest, opts ...grpc.CallOption) (*KvSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvSetResponse)
	err := c.cc.Invoke(ctx, CacheService_KvSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvGetResponse)
	err := c.cc.Invoke(ctx, CacheService_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) KvDel(ctx context.Context, in *KvDelRequest, opts ...grpc.CallOption) (*KvDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvDelResponse)
	err := c.cc.Invoke(ctx, CacheService_KvDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) KvExists(ctx context.Context, in *KvExistsRequest, opts ...grpc.CallOption) (*KvExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvExistsResponse)
	err := c.cc.Invoke(ctx, CacheService_KvExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashSet(ctx context.Context, in *HashSetRequest, opts ...grpc.CallOption) (*HashSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashSetResponse)
	err := c.cc.Invoke(ctx, CacheService_HashSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashGet(ctx context.Context, in *HashGetRequest, opts ...grpc.CallOption) (*HashGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashGetResponse)
	err := c.cc.Invoke(ctx, CacheService_HashGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashDel(ctx context.Context, in *HashDelRequest, opts ...grpc.CallOption) (*HashDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashDelResponse)
	err := c.cc.Invoke(ctx, CacheService_HashDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashExists(ctx context.Context, in *HashExistsRequest, opts ...grpc.CallOption) (*HashExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashExistsResponse)
	err := c.cc.Invoke(ctx, CacheService_HashExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashLen(ctx context.Context, in *HashLenRequest, opts ...grpc.CallOption) (*HashLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashLenResponse)
	err := c.cc.Invoke(ctx, CacheService_HashLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashSetM(ctx context.Context, in *HashSetMRequest, opts ...grpc.CallOption) (*HashSetMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashSetMResponse)
	err := c.cc.Invoke(ctx, CacheService_HashSetM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashGetM(ctx context.Context, in *HashGetMRequest, opts ...grpc.CallOption) (*HashGetMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashGetMResponse)
	err := c.cc.Invoke(ctx, CacheService_HashGetM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashDelM(ctx context.Context, in *HashDelMRequest, opts ...grpc.CallOption) (*HashDelMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashDelMResponse)
	err := c.cc.Invoke(ctx, CacheService_HashDelM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HashExistsM(ctx context.Context, in *HashExistsMRequest, opts ...grpc.CallOption) (*HashExistsMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashExistsMResponse)
	err := c.cc.Invoke(ctx, CacheService_HashExistsM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetSet(ctx context.Context, in *SetSetRequest, opts ...grpc.CallOption) (*SetSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSetResponse)
	err := c.cc.Invoke(ctx, CacheService_SetSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetGet(ctx context.Context, in *SetGetRequest, opts ...grpc.CallOption) (*SetGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGetResponse)
	err := c.cc.Invoke(ctx, CacheService_SetGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetDel(ctx context.Context, in *SetDelRequest, opts ...grpc.CallOption) (*SetDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDelResponse)
	err := c.cc.Invoke(ctx, CacheService_SetDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetExists(ctx context.Context, in *SetExistsRequest, opts ...grpc.CallOption) (*SetExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetExistsResponse)
	err := c.cc.Invoke(ctx, CacheService_SetExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetLen(ctx context.Context, in *SetLenRequest, opts ...grpc.CallOption) (*SetLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLenResponse)
	err := c.cc.Invoke(ctx, CacheService_SetLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetAddM(ctx context.Context, in *SetAddMRequest, opts ...grpc.CallOption) (*SetAddMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAddMResponse)
	err := c.cc.Invoke(ctx, CacheService_SetAddM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetExistsM(ctx context.Context, in *SetExistsMRequest, opts ...grpc.CallOption) (*SetExistsMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetExistsMResponse)
	err := c.cc.Invoke(ctx, CacheService_SetExistsM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetDelM(ctx context.Context, in *SetDelMRequest, opts ...grpc.CallOption) (*SetDelMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDelMResponse)
	err := c.cc.Invoke(ctx, CacheService_SetDelM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SetGetM(ctx context.Context, in *SetGetMRequest, opts ...grpc.CallOption) (*SetGetMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGetMResponse)
	err := c.cc.Invoke(ctx, CacheService_SetGetM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Set(ctx context.Context, in *KvSetRequest, opts ...grpc.CallOption) (*KvSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvSetResponse)
	err := c.cc.Invoke(ctx, CacheService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Get(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvGetResponse)
	err := c.cc.Invoke(ctx, CacheService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Del(ctx context.Context, in *KvDelRequest, opts ...grpc.CallOption) (*KvDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvDelResponse)
	err := c.cc.Invoke(ctx, CacheService_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Exists(ctx context.Context, in *KvExistsRequest, opts ...grpc.CallOption) (*KvExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvExistsResponse)
	err := c.cc.Invoke(ctx, CacheService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HMSet(ctx context.Context, in *HashSetMRequest, opts ...grpc.CallOption) (*HashSetMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashSetMResponse)
	err := c.cc.Invoke(ctx, CacheService_HMSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HMGet(ctx context.Context, in *HashGetMRequest, opts ...grpc.CallOption) (*HashGetMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashGetMResponse)
	err := c.cc.Invoke(ctx, CacheService_HMGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HLen(ctx context.Context, in *HashLenRequest, opts ...grpc.CallOption) (*HashLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashLenResponse)
	err := c.cc.Invoke(ctx, CacheService_HLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HGetAll(ctx context.Context, in *HashGetRequest, opts ...grpc.CallOption) (*HashGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashGetResponse)
	err := c.cc.Invoke(ctx, CacheService_HGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HDel(ctx context.Context, in *HashDelRequest, opts ...grpc.CallOption) (*HashDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashDelResponse)
	err := c.cc.Invoke(ctx, CacheService_HDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) HExists(ctx context.Context, in *HashExistsMRequest, opts ...grpc.CallOption) (*HashExistsMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashExistsMResponse)
	err := c.cc.Invoke(ctx, CacheService_HExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SAdd(ctx context.Context, in *SetAddMRequest, opts ...grpc.CallOption) (*SetAddMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAddMResponse)
	err := c.cc.Invoke(ctx, CacheService_SAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SIsMember(ctx context.Context, in *SetExistsMRequest, opts ...grpc.CallOption) (*SetExistsMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetExistsMResponse)
	err := c.cc.Invoke(ctx, CacheService_SIsMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SCard(ctx context.Context, in *SetLenRequest, opts ...grpc.CallOption) (*SetLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLenResponse)
	err := c.cc.Invoke(ctx, CacheService_SCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SMembers(ctx context.Context, in *SetGetRequest, opts ...grpc.CallOption) (*SetGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGetResponse)
	err := c.cc.Invoke(ctx, CacheService_SMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) SRem(ctx context.Context, in *SetDelMRequest, opts ...grpc.CallOption) (*SetDelMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDelMResponse)
	err := c.cc.Invoke(ctx, CacheService_SRem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LPush(ctx context.Context, in *LPushRequest, opts ...grpc.CallOption) (*LPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LPushResponse)
	err := c.cc.Invoke(ctx, CacheService_LPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LRange(ctx context.Context, in *LRangeRequest, opts ...grpc.CallOption) (*LRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LRangeResponse)
	err := c.cc.Invoke(ctx, CacheService_LRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LRem(ctx context.Context, in *LRemRequest, opts ...grpc.CallOption) (*LRemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LRemResponse)
	err := c.cc.Invoke(ctx, CacheService_LRem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LPop(ctx context.Context, in *LPopRequest, opts ...grpc.CallOption) (*LPopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LPopResponse)
	err := c.cc.Invoke(ctx, CacheService_LPop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) RPush(ctx context.Context, in *RPushRequest, opts ...grpc.CallOption) (*RPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RPushResponse)
	err := c.cc.Invoke(ctx, CacheService_RPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) RPop(ctx context.Context, in *RPopRequest, opts ...grpc.CallOption) (*RPopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RPopResponse)
	err := c.cc.Invoke(ctx, CacheService_RPop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LLen(ctx context.Context, in *LLenRequest, opts ...grpc.CallOption) (*LLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLenResponse)
	err := c.cc.Invoke(ctx, CacheService_LLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LIndex(ctx context.Context, in *LIndexRequest, opts ...grpc.CallOption) (*LIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LIndexResponse)
	err := c.cc.Invoke(ctx, CacheService_LIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) LSet(ctx context.Context, in *LSetRequest, opts ...grpc.CallOption) (*LSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LSetResponse)
	err := c.cc.Invoke(ctx, CacheService_LSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServiceServer is the server API for CacheService service.
// All implementations must embed UnimplementedCacheServiceServer
// for forward compatibility.
//
// CacheService provides Redis-like cache operations
type CacheServiceServer interface {
	// ---------- KV Native Operations ----------
	KvSet(context.Context, *KvSetRequest) (*KvSetResponse, error)
	KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error)
	KvDel(context.Context, *KvDelRequest) (*KvDelResponse, error)
	KvExists(context.Context, *KvExistsRequest) (*KvExistsResponse, error)
	// ---------- Hash Native Operations ----------
	// Batch/whole hash operations
	HashSet(context.Context, *HashSetRequest) (*HashSetResponse, error)
	HashGet(context.Context, *HashGetRequest) (*HashGetResponse, error)
	HashDel(context.Context, *HashDelRequest) (*HashDelResponse, error)
	HashExists(context.Context, *HashExistsRequest) (*HashExistsResponse, error)
	HashLen(context.Context, *HashLenRequest) (*HashLenResponse, error)
	// Single field operations
	HashSetM(context.Context, *HashSetMRequest) (*HashSetMResponse, error)
	HashGetM(context.Context, *HashGetMRequest) (*HashGetMResponse, error)
	HashDelM(context.Context, *HashDelMRequest) (*HashDelMResponse, error)
	HashExistsM(context.Context, *HashExistsMRequest) (*HashExistsMResponse, error)
	// ---------- Set Native Operations ----------
	// Batch/whole set operations
	SetSet(context.Context, *SetSetRequest) (*SetSetResponse, error)
	SetGet(context.Context, *SetGetRequest) (*SetGetResponse, error)
	SetDel(context.Context, *SetDelRequest) (*SetDelResponse, error)
	SetExists(context.Context, *SetExistsRequest) (*SetExistsResponse, error)
	SetLen(context.Context, *SetLenRequest) (*SetLenResponse, error)
	// Single member operations
	SetAddM(context.Context, *SetAddMRequest) (*SetAddMResponse, error)
	SetExistsM(context.Context, *SetExistsMRequest) (*SetExistsMResponse, error)
	SetDelM(context.Context, *SetDelMRequest) (*SetDelMResponse, error)
	SetGetM(context.Context, *SetGetMRequest) (*SetGetMResponse, error)
	// ---------- KV Redis Aliases ----------
	// SET -> forwards to KvSet
	Set(context.Context, *KvSetRequest) (*KvSetResponse, error)
	// GET -> forwards to KvGet
	Get(context.Context, *KvGetRequest) (*KvGetResponse, error)
	// DEL -> forwards to KvDel
	Del(context.Context, *KvDelRequest) (*KvDelResponse, error)
	// EXISTS -> forwards to KvExists
	Exists(context.Context, *KvExistsRequest) (*KvExistsResponse, error)
	// ---------- Hash Redis Aliases ----------
	// HMSET -> forwards to HashSetM (set single field)
	HMSet(context.Context, *HashSetMRequest) (*HashSetMResponse, error)
	// HMGET -> forwards to HashGetM (get single field)
	HMGet(context.Context, *HashGetMRequest) (*HashGetMResponse, error)
	// HLEN -> forwards to HashLen
	HLen(context.Context, *HashLenRequest) (*HashLenResponse, error)
	// HGETALL -> forwards to HashGet (get all fields)
	HGetAll(context.Context, *HashGetRequest) (*HashGetResponse, error)
	// HDEL -> forwards to HashDel (delete entire hash)
	HDel(context.Context, *HashDelRequest) (*HashDelResponse, error)
	// HEXISTS -> forwards to HashExistsM (check field exists)
	HExists(context.Context, *HashExistsMRequest) (*HashExistsMResponse, error)
	// ---------- Set Redis Aliases ----------
	// SADD -> forwards to SetAddM (add single member)
	SAdd(context.Context, *SetAddMRequest) (*SetAddMResponse, error)
	// SISMEMBER -> forwards to SetExistsM (check member exists)
	SIsMember(context.Context, *SetExistsMRequest) (*SetExistsMResponse, error)
	// SCARD -> forwards to SetLen (get member count)
	SCard(context.Context, *SetLenRequest) (*SetLenResponse, error)
	// SMEMBERS -> forwards to SetGet (get all members)
	SMembers(context.Context, *SetGetRequest) (*SetGetResponse, error)
	// SREM -> forwards to SetDelM (remove single member)
	SRem(context.Context, *SetDelMRequest) (*SetDelMResponse, error)
	// List operations
	LPush(context.Context, *LPushRequest) (*LPushResponse, error)
	LRange(context.Context, *LRangeRequest) (*LRangeResponse, error)
	LRem(context.Context, *LRemRequest) (*LRemResponse, error)
	LPop(context.Context, *LPopRequest) (*LPopResponse, error)
	RPush(context.Context, *RPushRequest) (*RPushResponse, error)
	RPop(context.Context, *RPopRequest) (*RPopResponse, error)
	LLen(context.Context, *LLenRequest) (*LLenResponse, error)
	LIndex(context.Context, *LIndexRequest) (*LIndexResponse, error)
	LSet(context.Context, *LSetRequest) (*LSetResponse, error)
	mustEmbedUnimplementedCacheServiceServer()
}

// UnimplementedCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheServiceServer struct{}

func (UnimplementedCacheServiceServer) KvSet(context.Context, *KvSetRequest) (*KvSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvSet not implemented")
}
func (UnimplementedCacheServiceServer) KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedCacheServiceServer) KvDel(context.Context, *KvDelRequest) (*KvDelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvDel not implemented")
}
func (UnimplementedCacheServiceServer) KvExists(context.Context, *KvExistsRequest) (*KvExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvExists not implemented")
}
func (UnimplementedCacheServiceServer) HashSet(context.Context, *HashSetRequest) (*HashSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashSet not implemented")
}
func (UnimplementedCacheServiceServer) HashGet(context.Context, *HashGetRequest) (*HashGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashGet not implemented")
}
func (UnimplementedCacheServiceServer) HashDel(context.Context, *HashDelRequest) (*HashDelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashDel not implemented")
}
func (UnimplementedCacheServiceServer) HashExists(context.Context, *HashExistsRequest) (*HashExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashExists not implemented")
}
func (UnimplementedCacheServiceServer) HashLen(context.Context, *HashLenRequest) (*HashLenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashLen not implemented")
}
func (UnimplementedCacheServiceServer) HashSetM(context.Context, *HashSetMRequest) (*HashSetMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashSetM not implemented")
}
func (UnimplementedCacheServiceServer) HashGetM(context.Context, *HashGetMRequest) (*HashGetMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashGetM not implemented")
}
func (UnimplementedCacheServiceServer) HashDelM(context.Context, *HashDelMRequest) (*HashDelMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashDelM not implemented")
}
func (UnimplementedCacheServiceServer) HashExistsM(context.Context, *HashExistsMRequest) (*HashExistsMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HashExistsM not implemented")
}
func (UnimplementedCacheServiceServer) SetSet(context.Context, *SetSetRequest) (*SetSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSet not implemented")
}
func (UnimplementedCacheServiceServer) SetGet(context.Context, *SetGetRequest) (*SetGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGet not implemented")
}
func (UnimplementedCacheServiceServer) SetDel(context.Context, *SetDelRequest) (*SetDelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDel not implemented")
}
func (UnimplementedCacheServiceServer) SetExists(context.Context, *SetExistsRequest) (*SetExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetExists not implemented")
}
func (UnimplementedCacheServiceServer) SetLen(context.Context, *SetLenRequest) (*SetLenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLen not implemented")
}
func (UnimplementedCacheServiceServer) SetAddM(context.Context, *SetAddMRequest) (*SetAddMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAddM not implemented")
}
func (UnimplementedCacheServiceServer) SetExistsM(context.Context, *SetExistsMRequest) (*SetExistsMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetExistsM not implemented")
}
func (UnimplementedCacheServiceServer) SetDelM(context.Context, *SetDelMRequest) (*SetDelMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDelM not implemented")
}
func (UnimplementedCacheServiceServer) SetGetM(context.Context, *SetGetMRequest) (*SetGetMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGetM not implemented")
}
func (UnimplementedCacheServiceServer) Set(context.Context, *KvSetRequest) (*KvSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedCacheServiceServer) Get(context.Context, *KvGetRequest) (*KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCacheServiceServer) Del(context.Context, *KvDelRequest) (*KvDelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedCacheServiceServer) Exists(context.Context, *KvExistsRequest) (*KvExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedCacheServiceServer) HMSet(context.Context, *HashSetMRequest) (*HashSetMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HMSet not implemented")
}
func (UnimplementedCacheServiceServer) HMGet(context.Context, *HashGetMRequest) (*HashGetMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HMGet not implemented")
}
func (UnimplementedCacheServiceServer) HLen(context.Context, *HashLenRequest) (*HashLenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HLen not implemented")
}
func (UnimplementedCacheServiceServer) HGetAll(context.Context, *HashGetRequest) (*HashGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HGetAll not implemented")
}
func (UnimplementedCacheServiceServer) HDel(context.Context, *HashDelRequest) (*HashDelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HDel not implemented")
}
func (UnimplementedCacheServiceServer) HExists(context.Context, *HashExistsMRequest) (*HashExistsMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HExists not implemented")
}
func (UnimplementedCacheServiceServer) SAdd(context.Context, *SetAddMRequest) (*SetAddMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SAdd not implemented")
}
func (UnimplementedCacheServiceServer) SIsMember(context.Context, *SetExistsMRequest) (*SetExistsMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SIsMember not implemented")
}
func (UnimplementedCacheServiceServer) SCard(context.Context, *SetLenRequest) (*SetLenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SCard not implemented")
}
func (UnimplementedCacheServiceServer) SMembers(context.Context, *SetGetRequest) (*SetGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SMembers not implemented")
}
func (UnimplementedCacheServiceServer) SRem(context.Context, *SetDelMRequest) (*SetDelMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SRem not implemented")
}
func (UnimplementedCacheServiceServer) LPush(context.Context, *LPushRequest) (*LPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LPush not implemented")
}
func (UnimplementedCacheServiceServer) LRange(context.Context, *LRangeRequest) (*LRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LRange not implemented")
}
func (UnimplementedCacheServiceServer) LRem(context.Context, *LRemRequest) (*LRemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LRem not implemented")
}
func (UnimplementedCacheServiceServer) LPop(context.Context, *LPopRequest) (*LPopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LPop not implemented")
}
func (UnimplementedCacheServiceServer) RPush(context.Context, *RPushRequest) (*RPushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RPush not implemented")
}
func (UnimplementedCacheServiceServer) RPop(context.Context, *RPopRequest) (*RPopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RPop not implemented")
}
func (UnimplementedCacheServiceServer) LLen(context.Context, *LLenRequest) (*LLenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LLen not implemented")
}
func (UnimplementedCacheServiceServer) LIndex(context.Context, *LIndexRequest) (*LIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LIndex not implemented")
}
func (UnimplementedCacheServiceServer) LSet(context.Context, *LSetRequest) (*LSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LSet not implemented")
}
func (UnimplementedCacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {}
func (UnimplementedCacheServiceServer) testEmbeddedByValue()                      {}

// UnsafeCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheServiceServer will
// result in compilation errors.
type UnsafeCacheServiceServer interface {
	mustEmbedUnimplementedCacheServiceServer()
}

func RegisterCacheServiceServer(s grpc.ServiceRegistrar, srv CacheServiceServer) {
	// If the following call panics, it indicates UnimplementedCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheService_ServiceDesc, srv)
}

func _CacheService_KvSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).KvSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_KvSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).KvSet(ctx, req.(*KvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).KvGet(ctx, req.(*KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_KvDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).KvDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_KvDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).KvDel(ctx, req.(*KvDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_KvExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).KvExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_KvExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).KvExists(ctx, req.(*KvExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashSet(ctx, req.(*HashSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashGet(ctx, req.(*HashGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashDel(ctx, req.(*HashDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashExists(ctx, req.(*HashExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashLen(ctx, req.(*HashLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashSetM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashSetMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashSetM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashSetM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashSetM(ctx, req.(*HashSetMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashGetM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashGetMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashGetM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashGetM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashGetM(ctx, req.(*HashGetMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashDelM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashDelMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashDelM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashDelM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashDelM(ctx, req.(*HashDelMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HashExistsM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashExistsMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HashExistsM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HashExistsM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HashExistsM(ctx, req.(*HashExistsMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetSet(ctx, req.(*SetSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetGet(ctx, req.(*SetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetDel(ctx, req.(*SetDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetExists(ctx, req.(*SetExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetLen(ctx, req.(*SetLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetAddM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAddMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetAddM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetAddM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetAddM(ctx, req.(*SetAddMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetExistsM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExistsMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetExistsM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetExistsM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetExistsM(ctx, req.(*SetExistsMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetDelM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDelMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetDelM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetDelM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetDelM(ctx, req.(*SetDelMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SetGetM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGetMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SetGetM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SetGetM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SetGetM(ctx, req.(*SetGetMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Set(ctx, req.(*KvSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Get(ctx, req.(*KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Del(ctx, req.(*KvDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Exists(ctx, req.(*KvExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HMSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashSetMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HMSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HMSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HMSet(ctx, req.(*HashSetMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HMGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashGetMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HMGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HMGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HMGet(ctx, req.(*HashGetMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HLen(ctx, req.(*HashLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HGetAll(ctx, req.(*HashGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HDel(ctx, req.(*HashDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_HExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashExistsMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).HExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_HExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).HExists(ctx, req.(*HashExistsMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAddMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SAdd(ctx, req.(*SetAddMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SIsMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExistsMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SIsMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SIsMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SIsMember(ctx, req.(*SetExistsMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SCard(ctx, req.(*SetLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SMembers(ctx, req.(*SetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_SRem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDelMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).SRem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_SRem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).SRem(ctx, req.(*SetDelMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LPush(ctx, req.(*LPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LRange(ctx, req.(*LRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LRem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LRemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LRem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LRem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LRem(ctx, req.(*LRemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LPop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LPop(ctx, req.(*LPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_RPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).RPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_RPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).RPush(ctx, req.(*RPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_RPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).RPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_RPop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).RPop(ctx, req.(*RPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LLen(ctx, req.(*LLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LIndex(ctx, req.(*LIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_LSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).LSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_LSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).LSet(ctx, req.(*LSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheService_ServiceDesc is the grpc.ServiceDesc for CacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KvSet",
			Handler:    _CacheService_KvSet_Handler,
		},
		{
			MethodName: "KvGet",
			Handler:    _CacheService_KvGet_Handler,
		},
		{
			MethodName: "KvDel",
			Handler:    _CacheService_KvDel_Handler,
		},
		{
			MethodName: "KvExists",
			Handler:    _CacheService_KvExists_Handler,
		},
		{
			MethodName: "HashSet",
			Handler:    _CacheService_HashSet_Handler,
		},
		{
			MethodName: "HashGet",
			Handler:    _CacheService_HashGet_Handler,
		},
		{
			MethodName: "HashDel",
			Handler:    _CacheService_HashDel_Handler,
		},
		{
			MethodName: "HashExists",
			Handler:    _CacheService_HashExists_Handler,
		},
		{
			MethodName: "HashLen",
			Handler:    _CacheService_HashLen_Handler,
		},
		{
			MethodName: "HashSetM",
			Handler:    _CacheService_HashSetM_Handler,
		},
		{
			MethodName: "HashGetM",
			Handler:    _CacheService_HashGetM_Handler,
		},
		{
			MethodName: "HashDelM",
			Handler:    _CacheService_HashDelM_Handler,
		},
		{
			MethodName: "HashExistsM",
			Handler:    _CacheService_HashExistsM_Handler,
		},
		{
			MethodName: "SetSet",
			Handler:    _CacheService_SetSet_Handler,
		},
		{
			MethodName: "SetGet",
			Handler:    _CacheService_SetGet_Handler,
		},
		{
			MethodName: "SetDel",
			Handler:    _CacheService_SetDel_Handler,
		},
		{
			MethodName: "SetExists",
			Handler:    _CacheService_SetExists_Handler,
		},
		{
			MethodName: "SetLen",
			Handler:    _CacheService_SetLen_Handler,
		},
		{
			MethodName: "SetAddM",
			Handler:    _CacheService_SetAddM_Handler,
		},
		{
			MethodName: "SetExistsM",
			Handler:    _CacheService_SetExistsM_Handler,
		},
		{
			MethodName: "SetDelM",
			Handler:    _CacheService_SetDelM_Handler,
		},
		{
			MethodName: "SetGetM",
			Handler:    _CacheService_SetGetM_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _CacheService_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CacheService_Get_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _CacheService_Del_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _CacheService_Exists_Handler,
		},
		{
			MethodName: "HMSet",
			Handler:    _CacheService_HMSet_Handler,
		},
		{
			MethodName: "HMGet",
			Handler:    _CacheService_HMGet_Handler,
		},
		{
			MethodName: "HLen",
			Handler:    _CacheService_HLen_Handler,
		},
		{
			MethodName: "HGetAll",
			Handler:    _CacheService_HGetAll_Handler,
		},
		{
			MethodName: "HDel",
			Handler:    _CacheService_HDel_Handler,
		},
		{
			MethodName: "HExists",
			Handler:    _CacheService_HExists_Handler,
		},
		{
			MethodName: "SAdd",
			Handler:    _CacheService_SAdd_Handler,
		},
		{
			MethodName: "SIsMember",
			Handler:    _CacheService_SIsMember_Handler,
		},
		{
			MethodName: "SCard",
			Handler:    _CacheService_SCard_Handler,
		},
		{
			MethodName: "SMembers",
			Handler:    _CacheService_SMembers_Handler,
		},
		{
			MethodName: "SRem",
			Handler:    _CacheService_SRem_Handler,
		},
		{
			MethodName: "LPush",
			Handler:    _CacheService_LPush_Handler,
		},
		{
			MethodName: "LRange",
			Handler:    _CacheService_LRange_Handler,
		},
		{
			MethodName: "LRem",
			Handler:    _CacheService_LRem_Handler,
		},
		{
			MethodName: "LPop",
			Handler:    _CacheService_LPop_Handler,
		},
		{
			MethodName: "RPush",
			Handler:    _CacheService_RPush_Handler,
		},
		{
			MethodName: "RPop",
			Handler:    _CacheService_RPop_Handler,
		},
		{
			MethodName: "LLen",
			Handler:    _CacheService_LLen_Handler,
		},
		{
			MethodName: "LIndex",
			Handler:    _CacheService_LIndex_Handler,
		},
		{
			MethodName: "LSet",
			Handler:    _CacheService_LSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}
